name: Build and Publish build Docker Image

on:
  workflow_run:
    workflows: ["docker-patcher-publish"]
    types: [completed]

permissions:
  contents: read
  packages: write

env:
  PACKAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}/build

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set build date tag
        id: date
        run: |
          echo "build_date=$(date -u +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Image name lowercase
        run: |
          echo "IMAGE_NAME_LOWER=${IMAGE_NAME@L}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.PACKAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-build
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME_LOWER }}:latest
            ${{ env.IMAGE_NAME_LOWER }}:${{ steps.date.outputs.build_date }}
